# Generated by Django 4.1 on 2022-08-13 21:06

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('entrada', models.IntegerField()),
                ('modalidad', models.BooleanField()),
                ('lugar', models.CharField(max_length=255)),
                ('detalles', models.CharField(max_length=255)),
            ],
        ),
    ]
