# Generated by Django 4.1 on 2022-08-25 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_id_usuario_asistencia_id_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='id_Evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento'),
        ),
    ]
